#!/bin/sh

[ $# = 1 ] || exit 1

devpath=/sys/class/backlight/intel_backlight
max=$(cat $devpath/max_brightness)
cur=$(cat $devpath/brightness)

op=${1:0:1}
number=${1:1}

if [[ $op = + ]]; then
	disp=$(($number*$max/100))
	new=$(($cur+$disp))
elif [[ $op == - ]]; then
	disp=$(($number*$max/100))
	new=$(($cur-$disp))
else
	new=$(($1*$max/100))
fi

if [[ $new -lt 0 ]]; then
	new=0
elif [[ $new -gt $max ]]; then
	new=$max
fi

echo $new | sudo -A tee $devpath/brightness > /dev/null
