#!/bin/bash

[ $# = 1 ] || exit 1

devpath=/sys/class/backlight/intel_backlight
max=$(cat $devpath/max_brightness)
cur=$(cat $devpath/brightness)

op=${1:0:1}
number=${1:1}

disp=$(($number*$max/100))
if [[ $disp = 0 ]]; then
	exit 1
fi

if [[ $op = + ]]; then
	cur=$(($cur+$disp))
elif [[ $op == - ]]; then
	cur=$(($cur-$disp))
fi

if [[ $cur -lt 0 ]]; then
	cur=0
fi

echo $cur | sudo tee $devpath/brightness > /dev/null
