#!/bin/bash

file="${1?'No file given'}"
ext="${file##*.}"
lang="${2:-$ext}"
font="${3:-Courier10}"
out="${file%.*}.pdf"
[[ -e "$out" ]] && bak "$out"
enscript -B -C -E"$lang" -f"$font" --word-wrap -MLetter -p - "$file" |
	ps2pdf - "$out"

