#!/bin/sh

# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./dmenuprompt "Do you want to shutdown?" "shutdown -h now"`

# do not quote $@ since we *want* argument splitting
[ "$(printf "No\nYes" | dmenu -i -p "$1" )" \= "Yes" ] && shift && eval "$@"
