#!/usr/bin/env zsh
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

setopt sh_word_split

[ $(echo -e "No\nYes" | dmenu -i -p "$1" ) \= "Yes" ] && $2

