#!/bin/sh

pm() { pulsemixer "$@" --max-volume 100; }
alias ps='playerctl -p playerctld,spotify,chromium,%any'
alias mc=mediactl
np() { playerctl -l | grep -v playerctld | wc -l; }


case "${1:?no action}" in
# volume
mute)
	pm --mute;;
unmute)
	pm --unmute;;
toggle)
	pm --toggle-mute;;
[+-]*)
	pm --change-volume "$1";;
[0-9]*)
	pm --set-volume "$1";;

# player
play)
	ps play;;
pause)
	ps pause;;
play-pause)
	ps play-pause;;
pp)
	ps play-pause;;
next)
	ps next;;
previous)
	ps previous;;
prev)
	ps previous;;
status)
	ps status;;

shift)
	playerctld shift;;
shiftpp)
	playerctl -p playerctld pause &&
		sleep 0.2 &&
		playerctld shift &&
		playerctl -p playerctld play
	;;

# error
*)
	echo "invalid method" >&2
esac
