#!/usr/bin/env zsh

if type open_command >/dev/null; then
	case "$OSTYPE" in
	darwin*)
		command open "$@" &>/dev/null ;;
	*)
		(open_command "$@" &>/dev/null &) ;;
	esac
else
	echo "not implemented yet"
fi
