#!/bin/sh

pf="/tmp/playerctlstate"

for player in $(playerctl -l 2>/dev/null); do
	[ -z "$player" ] && continue
	status="$(playerctl -p "$player" status)"
	if [ "$status" = "Playing" ]; then
		echo "$player" > "$pf"
		exec playerctl -p "$player" "$@"
	fi
done

if [ -f "$pf" ]; then
	player="$(cat "$pf")"
	if [ -z "$player" ] || {
		status="$(playerctl -p "$player" status 2>/dev/null)";
		[ "$status" = "Stopped" ] ||
			! playerctl -p "$player" "$@"
	}; then
		rm -f "$pf"
		exec playerctlstate "$@"
	fi
else
	for player in $(playerctl -l 2>/dev/null); do
		[ -z "$player"  ] && continue
		status="$(playerctl -p "$player" status)"
		if [ "$status" != "Stopped" ]; then
			playerctl -p "$player" "$@" &&
				echo "$player" > "$pf"
			exit
		fi
	done
	exec playerctl "$@"
fi
