#!/bin/sh

set -e

lang="${1?}"
shift
tex=src.tex

cat <<EOF >"$tex"
\documentclass{article}
\usepackage{minted}
\usepackage[margin=0.75in]{geometry}

\newcommand{\src}[2]{
	\inputminted[
		autogobble,
		linenos,
		breaklines,
		python3=true,
		style=default,
		%stripnl,
		tabsize=8,
	]
	{#1}
	{#2}
}

\begin{document}
EOF
for arg; do
	file="$(readlink -f "$arg")"
	echo "\src{$lang}{$file}" >>"$tex"
done
echo "\end{document}" >>"$tex"
latexmk
