#!/bin/sh

host="https://tx.dovsalomon.com"
if [ $# -eq 0 ]; then
	printf "No arguments specified.\nUsage:\n transfer <file|directory>\n ... | transfer <file_name>\n" >&2
	return 1
fi
if tty -s; then
	file="$1"
	file_name="$(basename "$file")"
	if [ ! -e "$file" ]; then
		echo "$file: No such file or directory" >&2
		return 1
	fi
	if [ -d "$file" ]; then
		file_name="$file_name.zip"
		(cd "$file" && zip -r -q - .) | curl -#T- "$host/$file_name" | tee /dev/null
	else
		curl -#T- "$host/$file_name" <"$file" | tee /dev/null
	fi
else
	file_name=$1
	curl -#T- "$host/$file_name" | tee /dev/null
fi
