#!/bin/sh
if [ -z "$1" ]; then
	echo "Usage: transfer <file|directory>" >&2
	echo " ... | transfer <file_name>" >&2
	exit 1
fi
host="https://ix.dov.ms"
if tty -s; then
	file="$1"
	file_name="$(basename "$file")"
	if [ ! -e "$file" ]; then
		echo "^C to cancel, ^D to send." >&2
		curl -sT- "$host/$1" | tee /dev/null
	elif [ -d "$file" ]; then
		file_name="$file_name.zip"
		(cd "$file" && zip -r -q - .) | curl -#T- "$host/$file_name" | tee /dev/null
	else
		curl -#T "$file" "$host/$file_name" | tee /dev/null
	fi
else
	curl -#T- "$host/$1" | tee /dev/null
fi
