#!/bin/sh

case "$(uname)" in
Linux*)
	if [ -f /etc/os-release ]; then
		. /etc/os-release
	fi

	case $ID in
	arch)
		if command -v yay > /dev/null; then
			yay -Syu --noconfirm
		else
			sudo pacman -Syu
		fi
		;;
	ubuntu)
		sudo apt-get update &&
		sudo apt-get -y upgrade
		;;
	*)
		echo This linux distro is not supported
		exit 1
	esac
	;;
Darwin*)
	brew update && brew upgrade
	;;
esac

sudo -k
type upgrade_oh_my_zsh >/dev/null 2>&1 && upgrade_oh_my_zsh

