#!/bin/sh

[ -z "$1" ] && vpnconf='default' || vpnconf="$1"

if systemctl is-active "openvpn-client@$vpnconf" >/dev/null 2>&1; then
	printf "stopping..."
	sudo systemctl stop "openvpn-client@$vpnconf"
else
	printf "starting..."
	sudo systemctl start "openvpn-client@$vpnconf"
fi
printf "done\n"
